server:
  port: 8080

spring:
  application:
    name: KT

  #  security:
  #    user:
  #      name: user1
  #      password: 1234

  # Thymeleaf 설정
  thymeleaf:
    cache: false
    prefix: classpath:templates/views/

  # datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: kt326
    password: 1234

  # security 설정
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: UeuAoPpP4NMlQJtSmqbl
            client-secret: _crBHoQPNS
            scope:
              - email
              - public_profile
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


# MyBatis 매퍼(mapper) 파일 위치 설정
# src/main/resources 이하의 경로 지정
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

app:
  apikey: b3CqPrdJODsJ50VIR2GKwjIafLwOBKd%2BdK7EneQ6eX4mC5Jem3J8cZA5r2W30UwHv2kzFFAkLy10JaLggEKWZA%3D%3D
  clientId: UeuAoPpP4NMlQJtSmqbl
  clientSecret: _crBHoQPNS

  #OAuth2 Client 미사용
  oauth2:

    password: 1234


    # Kakao 로그인 관련 세팅값
    kakao:
      client-id: 6c931fa066b4c8b966c9a6fa7927442a # REST API 앱 키
      redirect-uri: http://localhost:8080/oauth2/kakao/callback # Redirect URI
      token-uri: https://kauth.kakao.com/oauth/token # access token 요청 URI
      user-info-uri: https://kapi.kakao.com/v2/user/me # 사용자 profile 요청 URI

  # 페이징 관련 세팅
  pagination:
    write_pages: 10  # 한 [페이징] 당 몇개의 페이지를 표시?
    page_rows: 10  # 한 [페이징] 당 몇개의 글을 리스트 할지?

  # 파일 업로드 경로
  upload:
    path: upload