server:
  port: 80

spring:
  application:
    name: KT

  # Thymeleaf 설정
  thymeleaf:
    cache: false
    prefix: classpath:templates/views/

  # datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${rds.username}
    password: ${rds.password}

  # security 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${rds.googleid}
            client-secret: ${rds.googlepassword}
            scope:
              - email
              - profile
            client-name: Google

          naver:
            client-id: ${rds.naverid}
            client-secret: ${rds.naverpassword}
            scope:
              - email
              - public_profile
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: ${rds.naverreuri}

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: name


# MyBatis 매퍼(mapper) 파일 위치 설정
# src/main/resources 이하의 경로 지정
mybatis:
  mapper-locations: classpath:mapper/**/*.xml


app:
  apikey: ${rds.apikey}
#  apikey: uat5K84UOgbyUpVijzoK5z5KSM%2FuFueqg%2Bs2VPWiF0KVRzT0CzCsV6c%2FEF0gP1LSzTnjg6coFJs8ww1dYsRnUw%3D%3D
#  apikey: 8BGhfSwTKBj6neg3z5U7kRvQgxhHVEATP%2BCRuEOJTl0ebB%2Fe1bfeDSDSU5yrkW%2FR4IxY4vlLH27Y3mF%2BUFNbJQ%3D%3D
#  apikey: n1QvK9orfdP8xNuB%2FXyp7YLMFD3%2Ffbm8E3MUf1MoGJG26eDEgi5b0%2F%2FJ2FqQPeWdlv%2BDT0bgX3hieCsmsTM7Tg%3D%3D
#  apikey: yX2naCE2GDeqRnAzSeOMSTLZuJ024sspBXv2a0bLRMRUj6s%2FQs6yX%2Fq1H4ELcAkS%2FkoSiCTmo%2BxvNv2SM1Gn0Q%3D%3D
  clientId : ${rds.naverblogid}
  clientSecret : ${rds.naverblogpassword}
  #OAuth2 Client 미사용
  oauth2:
    password: 1234

    # Kakao 로그인 관련 세팅값
    kakao:
      client-id: ${rds.kakaoid} # REST API 앱 키
      redirect-uri: ${rds.kakaoreuri} # Redirect URI
      token-uri: https://kauth.kakao.com/oauth/token # access token 요청 URI
      user-info-uri: https://kapi.kakao.com/v2/user/me # 사용자 profile 요청 URI

  # 페이징 관련 세팅
  pagination:
    write_pages: 10  # 한 [페이징] 당 몇개의 페이지를 표시?
    page_rows: 10  # 한 [페이징] 당 몇개의 글을 리스트 할지?

  # 파일 업로드 경로
  upload:
    path: upload


kakao:
  maps:
    api:
      key: ${rds.mapkey}
